name: Deploy MultiDocker

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      # befor install build docker image
      - run: docker build -t gokulcs4u/react-multi-test -f ./client/Dockerfile.dev ./client

      # run test scripts
      - run: docker run -e CI=true gokulcs4u/react-multi-test npm test -- --coverage

      # after install build other images and push to docker hub
      - run: docker build -t gokulcs4u/multi-client ./client
      - run: docker build -t gokulcs4u/multi-nginx ./nginx
      - run: docker build -t gokulcs4u/multi-server ./server
      - run: docker build -t gokulcs4u/multi-worker ./worker

      # after building images push to docker hub
      - run: docker push gokulcs4u/multi-client
      - run: docker push gokulcs4u/multi-nginx
      - run: docker push gokulcs4u/multi-server
      - run: docker push gokulcs4u/multi-worker

      # generate deployment package
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          region: ap-south-1
          application_name: multi-docker
          environment_name: Multi-docker-env
          existing_bucket_name: elasticbeanstalk-ap-south-1-092737449886
          version_label: "3"
          deployment_package: deploy.zip
      - name: Deployed!
        run: echo App deployed to ELB
